#!/usr/bin/env bash
#-*-coding:utf-8 -*-
#Auto updated?
#   Yes
#File:
#   husky-reboot-required
#Author:
#   The-Repo-Club [wayne6324@gmail.com]
#Github:
#   https://github.com/The-Repo-Club/
#
#Created:
#   Fri 09 September 2022, 04:08:49 PM [GMT+1]
#Modified:
#   Fri 09 September 2022, 06:10:02 PM [GMT+1]
#
#Description:
#   To be called from husky-reboot-required.hook.
#
#Dependencies:
#   bash, libnotify
#

GetUsers() { /usr/bin/users | sed 's| |\n|g' | sort | uniq ; }

_other_reboot_required() {
    local msg="Reboot is recommended due to the upgrade of core system package(s)."
    local title="Reboot recommended!"

    # at TTY
    echo "==> INFO: $msg" >&2

    # notification
    local user userid cmd

    for user in $(GetUsers) ; do
        userid=$(/usr/bin/id -u "$user")
        cmd=(
            DISPLAY=:0
            DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$userid"/bus
            /usr/bin/notify-send
            --icon=system-reboot
            --urgency=critical
            "'$title'"
            "'$msg'"
        )
        /usr/bin/su "$user" -c "${cmd[*]}"
    done
}
_other_reboot_required
unset -f _other_reboot_required